# -*- coding: utf-8 -*-
"""SimpleLinearRegression with ML libraries

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ImBuql8A-DaYwQJRz7YnxROJgi4lF2oE
"""

import numpy as  np
import pandas as pd
from sklearn import datasets, linear_model
import matplotlib.pyplot as plt

data = pd.read_csv("/content/Simple LinrRegrs eg data1.csv")
data.head()

x1=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

print(x1,y)

plt.plot(x1,y,'*b')
plt.title('before regression')
plt.show()

from sklearn.model_selection import train_test_split
x1_train,x1_test,y_train, y_test=train_test_split(x1,y,test_size=0.2,random_state=40)

from sklearn.linear_model import LinearRegression
regrsor=LinearRegression()
regrsor.fit(x1_train,y_train)

y_pred=regrsor.predict(x1_test)

df=pd.DataFrame({'Actual':y_test,'predicted':y_pred})
print("tested data \n",df)
y_pred=regrsor.predict(x1_train)
Df=pd.DataFrame({'Actual':y_train,'predicted':y_pred})
print("trained data")
Df

x=int(input("GIve some sample input as X:"))
print('The output is',float(regrsor.predict(np.array([x]).reshape(-1,1))))